server:
  port: 10091

spring:
  application:
    name: cloud-order-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8090

feign:
  sentinel:
    enabled: true
